version: '3.7'
services:
  binco-app-react:
    image: chavon/binco-app
    ports:
      - "4000:3000"
    restart: always
    networks:
      - bincocloud
  binco-services:
    image: chavon/binco-services
    ports:
      - "8085:8085"
    restart: always
    networks:
      - bincocloud
networks:
  bincocloud:
